### ISSUE TITLE
19/8/2022 นัดคุย (1st)

### ISSUE THREAD

**Issue by SukriTM** [SukriTM/Project-scratch-game#1]
- เเนวเกม [ตอนนี้คือ horror + puzzle ]
- สตอรี่บอร์ด เวอร์ชั่น 1
- เนื้อหาเกมประมาณเกมอะไร
- ตอบคำถามนี้ได้ 1.ดีกว่าเกมอื่นยังไง 2.เกมมีดีอะไร [ไว้ทีหลัง]

**Comment by kanonlas** [comment]
เเนวเกม : thrilling
เนื้อหา : วิ่งหนีผี มีทั้งหมด 5 ด่าน (เรียกเป็นตี 1 2 3 4 5)
เนื้อเรื่อง : รุ่นพี่แอบเเหกกฏกลับมาโซตัส ให้รุ่นน้องไปล่าท้าผี ปรากฏว่าเจอเเล้วต้องวิ่งหนีผี เอาตัวรอดให้ได้ 5 ด่าน
อาจมีการทำฉาก jump scare

**Comment by kanonlas** [comment]
ทำต่อหลังสอบ

1. สตอรี่บอร์ด 
2. ดีไซน์ตัวละคร ฉาก  
3. การทำสไลด์
