### ISSUE TITLE
Progression หลังการรายงานความคืบหน้า

### ISSUE THREAD

**Issue by SukriTM** [SukriTM/Project-scratch-game#11]
การอัพเดตโค้ด
การออกแบบ sprite และส่วนประกอบของเกม

**Comment by kanonlas** [comment]
https://drive.google.com/drive/folders/1-EoktnE5gRysvidohsVOdDU2jMpSdOPL?fbclid=IwAR0rth2yP_jx-6u9jAb7zOzRQU_1glQy32x6lb_USsz1ksTmHDbq-WUIPTg 
ออกเเบบผี เเละตัวละครพูดครึ่งหลัง

**Comment by kanonlas** [comment]
https://drive.google.com/drive/folders/1wZBMVAuMXpAM79InFgQvnbuB922oLLn-?fbclid=IwAR0rth2yP_jx-6u9jAb7zOzRQU_1glQy32x6lb_USsz1ksTmHDbq-WUIPTg อัพเดทบทพูด1

**Comment by kanonlas** [comment]
https://drive.google.com/drive/folders/1FYJ9wwWEZOtnGzPoNQRQhgdcR6eFr_T0?fbclid=IwAR0rth2yP_jx-6u9jAb7zOzRQU_1glQy32x6lb_USsz1ksTmHDbq-WUIPTg อัพเดทกล่อง บทพูด2

**Comment by kanonlas** [comment]
https://drive.google.com/drive/folders/13oYj_FAFLOZUTjFTyfMc2n2LbjKLLndI?fbclid=IwAR0rth2yP_jx-6u9jAb7zOzRQU_1glQy32x6lb_USsz1ksTmHDbq-WUIPTg บทพูดจบสุดท้าย

**Comment by kanonlas** [comment]
https://drive.google.com/drive/folders/1G99vpInmI0JhHSTYTLuGgoutuH3sR2iF?fbclid=IwAR0rth2yP_jx-6u9jAb7zOzRQU_1glQy32x6lb_USsz1ksTmHDbq-WUIPTg อัพเดทบทพูดครบเเล้ว เเละอัพเดทฉากจบ gamover เเบบปกติ

**Comment by SukriTM** [comment]
https://drive.google.com/drive/folders/1aNg1GucYMh6c-LV1K73qzIxqNKDEV0aR?usp=sharing
