### ISSUE TITLE
Background 

### ISSUE THREAD

**Issue by SukriTM** [SukriTM/Project-scratch-game#12]
สีพื้นถนน เทาดำประมาณนี่ครับ
![image](https://user-images.githubusercontent.com/110969497/190363583-98fdc5cc-36d1-46ab-9fed-10713d0006fd.png)

**Comment by THAMOLWAN771** [comment]
![Image200](https://user-images.githubusercontent.com/110970504/190486001-4589158d-92f7-43b6-8c80-0cefa857da2c.png)
ภาพรวมbackground

**Comment by kanonlas** [comment]
https://drive.google.com/drive/folders/1X6Ppg-mKnTnGVXx93HzOr-V3WyDJdJ5U?fbclid=IwAR0rth2yP_jx-6u9jAb7zOzRQU_1glQy32x6lb_USsz1ksTmHDbq-WUIPTg อัพเดทของตกเเต่งเเมพ
