### ISSUE TITLE
Sprite (ตัวตึกและสถานที่)

### ISSUE THREAD

**Issue by SukriTM** [SukriTM/Project-scratch-game#13]
-ทำสีขอบของตัวตึกแยกกัน
-ลานเกียร์ก็เป็น sprite เหมือนกันเลือกสีมาเลยก็ได้ (ทำขนาดพอๆกับแถบสีแดง) 
-สนามหญ้าทำเป็นสีเขียว สีเหลี่ยม กับ สี่เหลี่ยมผืนผ้า
-เส้นสีม่วงคือเส้นแบ่ง section มีทั้งหมด 6 ส่วน
-แถบสีแดงเป็น sprite ชิ้นใหญ่ ใช้สีเดียวกัน ใช้พื้นที่ต่อ section นึงซัก 30% ก็ได้มั้ง
![image](https://user-images.githubusercontent.com/110969497/190367053-31a3e885-9923-4011-bf84-08283cf7958a.png)

**Comment by SukriTM** [comment]
ตัวอาคารทรงประมาณนี้ก็ได้ครับ 
![image](https://user-images.githubusercontent.com/110969497/190367780-72045efc-4d85-4517-a28a-f7f54c1aa682.png)

**Comment by THAMOLWAN771** [comment]
สัดส่วนของสถานที่
![115](https://user-images.githubusercontent.com/110970504/190486497-dfa41524-6c37-4c99-9dba-d9d729fb844f.png)
![116](https://user-images.githubusercontent.com/110970504/190486517-efb8c178-8b58-48fd-9625-58c14fc1f0e9.png)
![111](https://user-images.githubusercontent.com/110970504/190486521-c9c2e4ed-a7e7-435f-bead-017a8d0b0c49.png)
![112](https://user-images.githubusercontent.com/110970504/190486525-bb021c84-b831-4e36-bbaa-f97bf169487b.png)
![113](https://user-images.githubusercontent.com/110970504/190486534-9b432b11-28d7-48c2-83f1-c7c9c88bfc2c.png)
![114](https://user-images.githubusercontent.com/110970504/190486540-7cd6455b-f4a9-4602-852a-8b75d409c181.png)

**Comment by THAMOLWAN771** [comment]
sprite (ตัวตึก+ต้นไม้)
![107](https://user-images.githubusercontent.com/110970504/190486726-9cb61467-db97-4b64-b0fa-ce2782fe5004.png)
![108](https://user-images.githubusercontent.com/110970504/190486733-8731f228-505b-46df-8983-5fce3b116806.png)
![101](https://user-images.githubusercontent.com/110970504/190486735-91a3b3eb-bb44-4342-ba3d-8a2dfeacfe65.png)
![102](https://user-images.githubusercontent.com/110970504/190486741-835b9360-e0bd-4478-a845-5f331b559f5c.png)
![103](https://user-images.githubusercontent.com/110970504/190486747-d4159361-10e5-4723-9f0c-29c3ab39014a.png)
![104](https://user-images.githubusercontent.com/110970504/190486748-4eb4a63d-ca83-46c5-b371-9cd2949d6932.png)
![105](https://user-images.githubusercontent.com/110970504/190486751-0a88ac70-0b36-40f2-973a-c177729f58ed.png)
![106](https://user-images.githubusercontent.com/110970504/190486752-9758d7fa-33b8-42a5-80c7-f9ee5a82cc22.png)

**Comment by kanonlas** [comment]
พอดีว่าลองทำตึกช่วยคุณฟิล์มดูไม่รู้ว่าเเบบนี้ได้ไหมครับ

**Comment by kanonlas** [comment]
![306837022_477058624298025_7079889326158518089_n](https://user-images.githubusercontent.com/110953327/190842582-9aa0831a-7a62-425f-a314-3f28efaac89e.jpg)

**Comment by SukriTM** [comment]
โอเคละครับๆ

**Comment by kanonlas** [comment]
https://drive.google.com/drive/folders/1FfZe8mg4kDFqbELWb6aGeMVx9G6vJTPj?fbclid=IwAR0rth2yP_jx-6u9jAb7zOzRQU_1glQy32x6lb_USsz1ksTmHDbq-WUIPTg ตึกไฟฟ้า กับโยธา

**Comment by kanonlas** [comment]
![306726992_3244729649125439_1356235707228271063_n](https://user-images.githubusercontent.com/110953327/190886633-31627416-da6e-45d9-bacd-8418533a1f97.jpg)

**Comment by kanonlas** [comment]
![306726016_598839555289990_3209575991884324783_n](https://user-images.githubusercontent.com/110953327/190886636-5bf0923a-bfe5-4cde-9df2-428a3d3305e1.jpg)

**Comment by THAMOLWAN771** [comment]
![306373387_602189164734329_6227744336907870951_n](https://user-images.githubusercontent.com/110970504/190892244-ddaaa124-9fec-466b-9b67-bc4fb20888eb.jpg)
![306874019_855648868751446_6468124941209956109_n](https://user-images.githubusercontent.com/110970504/190892247-3a3e3ef8-fb2b-4ea4-bdd8-91b3a81f569c.jpg)
![306907860_647991913328117_6428323275263761075_n](https://user-images.githubusercontent.com/110970504/190892249-ae33889b-8819-47fd-ab75-ac68a6f11d49.jpg)
![305615219_658040548752739_880730946800716589_n](https://user-images.githubusercontent.com/110970504/190892251-6625c278-0ce3-45d0-92d2-a50e448ca5f2.jpg)

**Comment by THAMOLWAN771** [comment]
ในอาคาร30ปี+ระเบียงชั้น4
![30y1](https://user-images.githubusercontent.com/110970504/190893880-5ea07611-e45d-4afe-b6e2-1412e2d13f6c.png)
![302](https://user-images.githubusercontent.com/110970504/190893886-a96e5ea7-2eab-4f24-8917-dc68182670f9.png)

**Comment by THAMOLWAN771** [comment]
ห้อง412/422
![412](https://user-images.githubusercontent.com/110970504/190893938-81406330-d54c-4609-8171-0bc58aacc7f1.png)
![422](https://user-images.githubusercontent.com/110970504/190893940-2b34bcb1-66a8-4804-b831-5a8af7d353dc.png)

**Comment by SukriTM** [comment]
https://drive.google.com/drive/folders/1t3N1FqK1wh4zXpMVT-XrXYU61TOLB3YG?usp=sharing
ตึกเพิ่มเติม
