### ISSUE TITLE
Slide presentation 

### ISSUE THREAD

**Issue by SukriTM** [SukriTM/Project-scratch-game#4]
Due date : 7 September 2022
เตรียมนำเสนอ - ให้นำเสนอโดยสร้างเป็น slide ตาม Template ที่กำหนดให้ คือ ประกอบด้วย 
ภาพร่างของโครงงานเมื่อทำเสร็จแล้ว - แสดงให้เห็นว่าเกมหน้าตาเป็นอย่างไร เล่นอย่างไร
การแบ่งงานของทีม - ใครทำหน้าที่อะไรบ้าง

**Comment by kanonlas** [comment]
https://docs.google.com/presentation/d/16PJPDhNLhAwM0CJnxI0PVmHLawxJXw67RJYyir5WZ7E/edit#slide=id.g151051f13e5_1_0

**Comment by kanonlas** [comment]
complete
