### ISSUE TITLE
การประชุมวันที่ 5/9/2022

### ISSUE THREAD

**Issue by SukriTM** [SukriTM/Project-scratch-game#5]
นัดคุยการทำสไลด์นำเสนอหัวข้อ 
-ภาพร่างของโครงงาน (story board)
-การแบ่งงานสมาชิก

**Comment by kanonlas** [comment]
https://docs.google.com/presentation/d/16PJPDhNLhAwM0CJnxI0PVmHLawxJXw67RJYyir5WZ7E/edit#slide=id.g153a41b5ac9_2_9

**Comment by jobpatiphan** [comment]
![image](https://user-images.githubusercontent.com/110966004/188476807-cff93a5a-5923-4918-bf9d-ff2cc0b22859.png)

**Comment by jobpatiphan** [comment]
สตอรี่บอร์ดประมาณนี้ได้ไหมครับ

**Comment by kanonlas** [comment]
เยี่ยมเลยครับ
@jobpatiphan

**Comment by kanonlas** [comment]
![E34C173D-060F-46ED-8B43-9B70F1B15F2E](https://user-images.githubusercontent.com/110953327/188478736-b6af805e-bb86-4433-8d16-ab5ed0d3a8c6.jpg)

**Comment by THAMOLWAN771** [comment]
สรุปการประชุม 
1.ประชุมอีกทีพรุ่งนี้ 12:30 น.
2.ตัวละคร+ฉาก พรุ่งนี้ 50%
