### ISSUE TITLE
การประชุมวันที่ 6/9/2022

### ISSUE THREAD

**Issue by SukriTM** [SukriTM/Project-scratch-game#6]
การอัพเดตความคืบหน้าของการนำเสนอหัวข้อโครงงาน

**Comment by jobpatiphan** [comment]
หน้าเริ่มเกมประมาณนี้ได้ไหมครับ
![IMG_0452](https://user-images.githubusercontent.com/110966004/188592726-d8d94787-0268-416e-aaf0-74e711f604cf.png)

**Comment by kanonlas** [comment]
[สตอรี่บอร์ด.pdf](https://github.com/akakcoco/Project-scratch-game/files/9498396/default.pdf)
